### ISSUE TITLE
Order status is not updated when status is changed from shipday

### ISSUE THREAD

**Issue by Jorgelig** [igniter-labs/ti-ext-shipday#1]
**Expected behavior:**
I can't find where to configure the webhook within shipday or what configuration is missing for shipday to send the status change to tastyigniter

**Actual behavior:**
(Describe actual behavior here)

**Reproduce steps:**
1. The customer places an order on tastyigniter
2. The delivery person from the shipday app makes the status changes
3. The customer still sees the first status on the tastyigniter confirmation page (https://www.myrestaurant.com/checkout/success/ID)

**Version:**
3.1.6

**Additional Information:**
(Additional information, if any)

**Comment by sampoyigi** [comment]
You must contact Shipday to have them configure the webhook for you; otherwise, TastyIgniter will be unaware of the status update.

**Comment by Jorgelig** [comment]
They already answered me on behalf of and asked me for the data:
```

Hello Jorgelig,

Share the following information to set up the webhook for your account.

1. Webhook endpoint
2. Token for verification
3. Email ID registered on the day of submission
```

It would be good to leave it in the documentation that we have to send them an email to register the webhook: To: support@shipday.freshdesk.com, CC: support@shipday.com

**Comment by sampoyigi** [comment]
Thank you. Feel free to send a PR to update the docs :)
